Filter datachunk
COOL-cohort/COOL pull request #114
Opened 2022-11-03 13:38 UTC by NLGithubWP

2022-11-21 04:56 UTC, Zrealshadow commented on cool-core/src/main/java/com/nus/cool/core/cohort/refactor/CohortProcessor.java
> +        return false;
BUG, should be true

2022-11-21 05:14 UTC, Zrealshadow commented on cool-core/src/main/java/com/nus/cool/core/cohort/refactor/CohortProcessor.java
> +
Is it finished ? It doesn't cover valueSelection and ageSelection, thus the process logic maybe lead to error. 
And according to the reference of this method, the return value is exactly the opposite. (True should be false, and false should be true)

2022-11-21 05:15 UTC, Zrealshadow commented on cool-core/src/main/java/com/nus/cool/core/cohort/refactor/CohortProcessor.java
> +
And there is no check for HashType filter

2022-11-21 05:30 UTC, Zrealshadow commented on cool-core/src/main/java/com/nus/cool/core/cohort/refactor/filter/RangeFilter.java
> +      if (u.isSubset(scope) || u.isIntersection(scope)) {
Error.
Filter [10,19) and input value [9,14) are intersection.
But Filter can not accept the [9, 14)

2022-11-21 05:31 UTC, Zrealshadow commented on cool-core/src/main/java/com/nus/cool/core/io/readstore/DataInvariantRangeFieldRS.java
> +  public DataInvariantRangeFieldRS(ByteBuffer buf, FieldType fieldType, int invariantIdx,
should add corresponding unit test

2022-11-21 05:32 UTC, Zrealshadow commented on cool-core/src/main/java/com/nus/cool/core/util/writer/NativeDataWriter.java
>  }
add new line

2022-11-21 05:37 UTC, Zrealshadow requested changes
Some logic should be think twice. These code may lead to Bug.
Using Meta-Info to speed up cohort query processing need more specific unit test. 
I doubt that current unit test can not cover the code branch in this part.
Maybe we should rename the `checkMetaField` into a more direct and understandable name,  for example `canSkipMetaField` ? 
This direct name can give a understandable hint for the returned value.

2022-11-21 05:44 UTC, Zrealshadow commented
Also, solve the conflict to dev branch

2022-11-22 06:29 UTC, KimballCai commented
also, please pass the code formatting check test.

2023-04-25 08:35 UTC, closed without merging