Fix time window effect on birth event selection range
COOL-cohort/COOL pull request #25
Opened 2022-04-05 13:56 UTC by hugy718

Fix #24

2022-04-05 14:06 UTC, hugy718 commented
@KimballCai found another potential issue. In the same function. The birthOffset assignment on L485 does not match the comment. It is returned via cohort. Not sure if this is working as expected.
I tried switching the condition to (birthoffset > offset) It only affected the query result in one result tuple `ExtendedResultTuple(cohort=((1960, 1970]), age=0, measure=1594.0, min=0.0, max=85.0, sum=11888.0, num=381.0)` by increasing the measure by 1. Others are the same.

2022-04-06 08:55 UTC, KimballCai requested changes
need to add the logic to filter users by the time winsow setting.

2022-04-06 08:55 UTC, KimballCai commented on cool-core/src/main/java/com/nus/cool/core/cohort/ExtendedCohortSelection.java
>  				int windowOffset;
we should filter users who do not have records for at least `wlen` days.

2022-04-17 18:08 UTC, KimballCai commented
Fix the issue #24 with the problem about the TimeWindow

2022-04-17 18:08 UTC, merged