Xlp
COOL-cohort/COOL pull request #42
Opened 2022-05-02 04:34 UTC by qlinsey

added  iceberg related tests

2022-05-02 08:12 UTC, KimballCai commented
I have checked your code and there are several bugs. I have pushed a new commit to your repo and you can check it. If it is correct, please merge it in your repo.

Besides, please check all your commits and clean useless imports or codes that are not used. And please also check your output log.

2022-05-03 06:25 UTC, KimballCai commented
Please check that you can compile the code correctly.

2022-05-03 23:17 UTC, qlinsey commented
I removed csv loader related files following PR #39. pushed changes to my remote branch.

2022-05-04 04:44 UTC, KimballCai commented
Thanks. This repo runs smoothly on my machine, but please clean the updates that are not used in `cool-core/src/test/java/com/nus/cool/core/model/CoolModelTest.java`.

2022-05-04 04:45 UTC, KimballCai requested changes
clean the codes that are not used

2022-05-04 05:41 UTC, qlinsey commented on cool-core/src/test/java/com/nus/cool/core/model/CoolModelTest.java
> +import static org.testng.Assert.assertEquals;
removed, thanks!

2022-05-04 05:43 UTC, qlinsey reviewed
removed the unused package

2022-05-04 08:13 UTC, KimballCai approved these changes
All test cases pass.

2022-05-04 16:53 UTC, qlinsey commented
Should i close this pull request? thanks

2022-05-05 02:51 UTC, Zrealshadow reviewed
No meaningful modification in file `CoolModelTest.java`.

for the unittest of IcebergQuery and IcebergSekection, would you mind adding a DataProvider method, defining some static variables in DataProvider and input these as args for unittest method. You can check `HashFieldTest` file. In this layout your unittest will be more scalable, we can add other test data easily.

2022-05-05 05:05 UTC, KimballCai commented
Lingze @Zrealshadow has some other comments on your repo about the code format. 

No need to manually close the PR, and we will merge your PR after your modification.

Thanks

2022-05-05 05:49 UTC, qlinsey commented
Sure , I will take a look.

2022-05-06 05:21 UTC, qlinsey commented
I added DataProvider for two test cases in above, pls check . not sure where else I should add. Thanks.

2022-05-06 07:36 UTC, Zrealshadow reviewed
Thanks for your PR. The tests works in my side.
However, there are some improvements.
Firstly, I have to point that these tests is not automatic test. Actually, you should add some assert to compare the result you get and you expect. In your test, you just print these result and judge it manually.
Secondly, I think you should separate the test logic part from test data input part completely for  future scalability. For example, in you `IcebergQueryTest` , you set `@BeforeMethod` annotation in `setUp` method, which means this method will be invoked before every test method. But what you do in `setUp` is just setting some properties for one of your unit test. Obviously, if we add other test method, you have to change this part of code.

2022-05-06 07:40 UTC, Zrealshadow commented
> Thanks for your PR. The tests works in my side. However, there are some improvements. Firstly, I have to point that these tests is not automatic test. Actually, you should add some assert to compare the result you get and you expect. In your test, you just print these result and judge it manually. Secondly, I think you should separate the test logic part from test data input part completely for future scalability. For example, in you `IcebergQueryTest` , you set `@BeforeMethod` annotation in `setUp` method, which means this method will be invoked before every test method. But what you do in `setUp` is just setting some properties for one of your unit test. Obviously, if we add other test method, you have to change this part of code.

@KimballCai  No error in these code, I think we can merge it. but it's not automatic test. these code should be refactored and improved in the future.

2022-05-06 07:46 UTC, Zrealshadow commented
> I added DataProvider for two test cases in above, pls check . not sure where else I should add. Thanks.

The modification in file `CoolModelTest.java` doesn't make sense. Delete this commit. 
Then, We can merge it.

2022-05-06 07:47 UTC, Zrealshadow commented
> > I added DataProvider for two test cases in above, pls check . not sure where else I should add. Thanks.
@qlinsey
The modification in file `CoolModelTest.java` doesn't make sense. Delete this commit.
Then, We can merge it.

2022-05-07 03:29 UTC, qlinsey commented
> > I added DataProvider for two test cases in above, pls check . not sure where else I should add. Thanks.
> 
> @qlinsey The modification in file `CoolModelTest.java` doesn't make sense. Delete this commit. Then, We can merge it.



> 
Questions: 
(1) I read CoolModelTest.java, is there any difference from CubeListTest() vs. what I wrote? Does it also require Assert for Array of String?  For IcebergQueryTest, do you suggest me to add AssertEqual to json string? 
(2) I can move IcebergQuery initialization from setUp() to ToStringTest() method, please let me know. thanks.
(3) For CoolModelTest.java, I think that is because I removed the test cases, some more blank lines added. Let me try to remove. Thanks

2022-05-07 04:36 UTC, KimballCai commented
> > > I added DataProvider for two test cases in above, pls check . not sure where else I should add. Thanks.
> > 
> > 
> > @qlinsey The modification in file `CoolModelTest.java` doesn't make sense. Delete this commit. Then, We can merge it.
> 
> > 
> 
> Questions: (1) I read CoolModelTest.java, is there any difference from CubeListTest() vs. what I wrote?

please check https://github.com/COOL-cohort/COOL/pull/42/files

> Does it also require Assert for Array of String? For IcebergQueryTest, do you suggest me to add AssertEqual to json string? (2) I can move IcebergQuery initialization from setUp() to ToStringTest() method, please let me know. thanks. (3) For CoolModelTest.java, I think that is because I removed the test cases, some more blank lines added. Let me try to remove. Thanks

2022-05-07 05:12 UTC, qlinsey commented
@KimballCai  removed blank lines. thanks

2022-05-07 05:39 UTC, KimballCai commented
> > Thanks for your PR. The tests works in my side. However, there are some improvements. Firstly, I have to point that these tests is not automatic test. Actually, you should add some assert to compare the result you get and you expect. In your test, you just print these result and judge it manually. Secondly, I think you should separate the test logic part from test data input part completely for future scalability. For example, in you `IcebergQueryTest` , you set `@BeforeMethod` annotation in `setUp` method, which means this method will be invoked before every test method. But what you do in `setUp` is just setting some properties for one of your unit test. Obviously, if we add other test method, you have to change this part of code.
> 
> @KimballCai No error in these code, I think we can merge it. but it's not automatic test. these code should be refactored and improved in the future.

noted

2022-05-07 05:39 UTC, merged

2022-05-07 05:43 UTC, qlinsey commented
thanks, will delete branch.