Add metaChunk filter
COOL-cohort/COOL pull request #89
Opened 2022-08-15 13:05 UTC by NLGithubWP

Skip cublet by checking metaChunk with following rules
1. if any field' value in `birthEvents` is not in metaChunk, then no record will birth, so skip the Cubelet. 
2. If the field's value in the cohortSelector is not in metaChunk, then all birthed records cannot be assigned to any cohort; skip the Cubelet. 
3. if the value of any fields in `valueSelector` is not in metaChunk, then even if there are birthed records and cohort, all calculating results are empty; skip the Cubelet.

2022-09-01 12:27 UTC, Zrealshadow requested changes

2022-09-01 12:27 UTC, Zrealshadow commented on cool-core/src/main/java/com/nus/cool/core/cohort/refactor/filter/Filter.java
> +    public BitSet acceptIntList(List<Integer> values) throws RuntimeException;
No need to add type in function name

2022-09-01 12:27 UTC, Zrealshadow commented on cool-core/src/main/java/com/nus/cool/core/cohort/refactor/CohortProcessor.java
> +        this.layout = layout;
layout won't be used in future. Seperate the IO layer and logic layer
The memory of layout is allowed to be reclaimed.

2022-09-01 17:25 UTC, Zrealshadow requested changes
Correct the `accept(Scope)` logic, clean the code and make sure no warnings.
Then, we can merge this PR

2022-09-01 17:25 UTC, Zrealshadow commented on cool-core/src/main/java/com/nus/cool/core/cohort/refactor/filter/SetFilter.java
> +        List<String> listArr = Arrays.asList(values);
No need to transfer String[] to List<String>. Directly use String[]

2022-09-01 17:25 UTC, Zrealshadow commented on cool-core/src/main/java/com/nus/cool/core/cohort/refactor/storage/Scope.java
> +        return !(scope.getLeft() > right || scope.getRight() < left);
pay attention [left, right)
Wrong logic.
scope.getLeft() >= this.right || scope.getRight() <= this.left

2022-09-01 17:25 UTC, Zrealshadow commented on cool-core/src/main/java/com/nus/cool/core/cohort/refactor/birthSelect/EventSelection.java
> +    public List<Filter> getFilterList(){
Just using @Getter is better

2022-09-02 04:03 UTC, NLGithubWP commented on cool-core/src/main/java/com/nus/cool/core/cohort/refactor/birthSelect/EventSelection.java
> +    public List<Filter> getFilterList(){
Updated

2022-09-02 04:27 UTC, Zrealshadow approved these changes

2022-09-02 04:28 UTC, merged